Repository MungGeMungGe/MungGeMungGe, pull requests merged in 2021-04, with the labels that each got.

#3 [Feat] 할일 기능 구현
  lib/main.dart
  lib/models/todo.dart
  lib/screens/components/todo-item.dart
  lib/screens/components/todo-list.dart
  lib/screens/todo.dart
Labels: Feat

#7 Feat/search
  lib/models/search-model.dart
  lib/screens/components/search-list.dart
  lib/screens/search.dart
  pubspec.yaml
Labels: Feat

#8 머지한 후, 정상 작동되도록 수정
  lib/screens/google_map.dart
Labels: Bug

#10 [BUG] google_map.dart - null safety
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  assets/database/localdb.sqlite
  lib/screens/google_map.dart
  pubspec.yaml
Labels: Bug

#12 장소 리스트 + 즐겨찾기 기능
  lib/models/mgFavorite.dart
  lib/models/mgLocation.dart
  lib/screens/location_list/components/location_item.dart
  lib/screens/location_list/location_list.dart
  pubspec.yaml
Labels: Feat

#14 [FEAT] 흡연장소 접근시 흡연횟수 자동추가 기능
  lib/models/location.dart
  lib/screens/components/google_map_dialog.dart
  lib/screens/google_map.dart
  lib/utils/bitmap_descriptor_from_icon_data.dart
  pubspec.yaml
Labels: Feat

#15 Tab Controller 적용
  lib/main.dart
  lib/screens/location_list/location_list.dart
  pubspec.yaml
Labels: Bug, Refactoring
